% -------------------------------------------------
% Appendix setup 
% -------------------------------------------------
% Start a partial table of content, list of tables and list of figures. 
\startcontents[sections]
\startlist[appBoot]{lof}
\startlist[appBoot]{lot}

\azappendix{Details of bootstrap analysis}\label{app:bootstrap} 

\printcontents[sections]{l}{1}{\section*{\contentsname}}
\printlist[appBoot]{lot}{}{\section*{\listtablename}}
\printlist[appBoot]{lof}{}{\section*{\listfigurename}}
\cleardoublepage

% -------------------------------------------------
% Start writing appendix here
% -------------------------------------------------



% -------------------------------------------------
% Stop writing appendix here, end the adding to the lists:
% -------------------------------------------------
\stopcontents[sections]
\stoplist[appBoot]{lof}
\stoplist[appBoot]{lot}
\cleardoublepage