\azappendix{Data specification file} \label{app:dataSpecificationFile} 

% -------------------------------------------------
% Start writing appendix here
% -------------------------------------------------
We need to think about how to best include this file. Should be discussed with Rob - can we get the orderform to give us a pdf perhaps? 

% -------------------------------------------------
% Stop writing appendix here
% -------------------------------------------------
\cleardoublepage