% No partial table of content, list of tables and list of figures needed for this appendix
\azappendix{SCM output file} \label{app:SCMOutputFile} 

% -------------------------------------------------
% Start writing appendix here
% -------------------------------------------------

Can we call some program that generates a pdf based on a txt file? 

% -------------------------------------------------
% Stop writing appendix here
% -------------------------------------------------
\cleardoublepage