\documentclass[letterpaper, 12pt]{azreport}
% az require 9-12 pt. Hence, allowed latex size functions are:  
% \footnotesize=10, \small=10.95, \normalsize=12 and \large=14.4

% Note: file size of a single PDF file is limited to 100 Megabyte (MB). 

% -------------------------------------------------
% knitr opts
% -------------------------------------------------
<<setup,echo=F,warning=F,message=F>>=
# Load package to find root directory
library(rprojroot)
# Dont echo the R code by default
knitr::opts_chunk$set(echo=F)
# Knit document from project level dir and 
knitr::opts_knit$set(root.dir=find_root(has_file("OpenProject.Rproj"))) 
# Do *not* use setwd within the script, it will not work.
@ 

% -------------------------------------------------
% Setup R environment
% -------------------------------------------------
% When compling/knitting this file a new R session is started. 
% Your global environment is not available
<<environmentPrep,echo=F,warning=F,message=F>>=
# source your .Rprofile to configure the Project Libraries
source(file.path(find_root(has_file("OpenProject.Rproj")), ".Rprofile"))
source(file.path('Report','Setup','environmentPrep.R'))
@ 

% -------------------------------------------------
% Specify paths to images (EDA, BaseModel, CovModel)
% -------------------------------------------------
\graphicspath{
{\Sexpr{file.path(paste0(".",resEDADir),"")}}  % "" at the end to ensure a trailing /
{\Sexpr{file.path(paste0(".",resBaseModelDir),"")}}
{\Sexpr{file.path(paste0(".",resCovModelDir),"")}}
{Images/} % other images, e.g. AZ logo
}

% -------------------------------------------------
% Load report-specific variables
% -------------------------------------------------
<<projVars, child='./Setup/setup.Rnw'>>=
@

% -------------------------------------------------
% Start of report
% -------------------------------------------------
\begin{document}
% Start TOC, LOF and LOT for main report
\startcontents[sections]
\startlist[main]{lof}
\startlist[main]{lot}

% add title page to toc
\phantomsection \addcontentsline{toc}{section}{Title page} 
\maketitle

% -------------------------------------------------
% TOC
% -------------------------------------------------
% add TOC to toc
\phantomsection \addcontentsline{toc}{section}{\contentsname}
\printcontents[sections]{}{1}
  {\section*{\contentsname} \thispagestyle{followingpage} \setlength{\parskip}{0pt}}

% -------------------------------------------------
% List of tables
% -------------------------------------------------
\printlist[main]{lot}{}{\section*{\listtablename} \thispagestyle{followingpage}}

% -------------------------------------------------
% List of figures
% -------------------------------------------------
\printlist[main]{lof}{}{\section*{\listfigurename} \thispagestyle{followingpage}}

% -------------------------------------------------
% List of appendices
% -------------------------------------------------
\listofapp
\cleardoublepage
 
% -------------------------------------------------
% List of abbreviations and special terms
% -------------------------------------------------
<<abbreviations, child='./Sections/abbreviations.Rnw'>>=
@

% -------------------------------------------------
% Executive summary
% -------------------------------------------------
<<executiveSummary, child='./Sections/executiveSummary.Rnw'>>=
@

% -------------------------------------------------
% Main text sections
% -------------------------------------------------
<<introduction, child='./Sections/introduction.Rnw'>>=
@

<<objectives, child='./Sections/objectives.Rnw'>>=
@

<<data, child='./Sections/data.Rnw'>>=
@

<<methods, child='./Sections/methods.Rnw'>>=
@

<<results, child='./Sections/results.Rnw'>>=
@

<<discussion, child='./Sections/discussion.Rnw'>>=
@

<<conclusions, child='./Sections/conclusions.Rnw'>>=
@

% -------------------------------------------------
% Bibliography
% -------------------------------------------------
\bibliographystyle{unsrtnat}		% style of bib
\bibliography{references} 			% name without the .bib
\cleardoublepage

% Stop the main TOC, LOF and LOT
\stopcontents[sections]
\stoplist[main]{lof}
\stoplist[main]{lot}

% -------------------------------------------------
% Appendices
% -------------------------------------------------
% Tell latex that these sections are appendices
% (reset counters to A,B,C etc)
\appendices

<<analysisPlan, child='./Appendices/analysisPlan.Rnw'>>=
@

<<dataSpecFile, child='./Appendices/dataSpecFile.Rnw'>>=
@

<<dataIssuesAndHandling, child='./Appendices/dataIssuesAndHandling.Rnw'>>=
@

<<additionalEDA, child='./Appendices/additionalEDA.Rnw'>>=
@

<<parameterEstimatesKeyModels, child='./Appendices/parameterEstimatesKeyModels.Rnw'>>=
@

<<GOFplots, child='./Appendices/GOFplots.Rnw'>>=
@

<<baseModelOutputFile, child='./Appendices/baseModelOutputFile.Rnw'>>=
@

<<SCMOutputFile, child='./Appendices/SCMOutputFile.Rnw'>>=
@

<<plotsForAppropriatenessFinalModel, child='./Appendices/plotsForAppropriatenessFinalModel.Rnw'>>=
@

<<finalModelOutputFile, child='./Appendices/finalModelOutputFile.Rnw'>>=
@

<<individualPlots, child='./Appendices/individualPlots.Rnw'>>=
@

<<outliers, child='./Appendices/outliers.Rnw'>>=
@

<<additionalVPC, child='./Appendices/additionalVPC.Rnw'>>=
@

<<bootstrapAnalysis, child='./Appendices/bootstrapAnalysis.Rnw'>>=
@

% -------------------------------------------------
% End of report
% -------------------------------------------------
\end{document}